// Copyright 2023 The flatgeobuf (Go) Authors. All rights reserved.
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.

// Package flat provides types generated by flatc from the FlatGeobuf
// FlatBuffers schema.
package flat
