package testdata

//go:generate ../../../script/testdata_embed.sh empty.fgb
// DO NOT EDIT. Code generated by testdata_embed.sh version 33c7467c340dfc8b64aee4f39e69c704ce29ab56.
//
// This string contains the base64-encoded, bzip2-compressed, contents of the
// file `empty.fgb`. For license information, please see
// https://github.com/gogama/flatgeobuf/flatgeobuf/testdata/flatgeobuf/LICENSE.
//
// Last generated by schapper on Mon 18 Dec 2023 10:14:11 AM PST. The raw source
// SHA-256 is bdc45e249e4418ef95a69b55a6db523f035231fef2c61dded2bb26fc9e64070d.
//
// This silly byte-embedding trick is needed to access the example test code
// when running example code within the docs website,
// https://pkg.go.dev/github.com/gogama/flatgeobuf.
var EmptyFGB = `
QlpoOTFBWSZTWa7whNgAAeD/+//9RFBUZ3/gPufe6r/v/7AQAEABBABAAUABAQAEAMACNwknYDjQ0DRpkaaNMgMTBAADQGgNMgMCZAyiTwKY0SeTSAAAAABkAA0AAAImiagBoBoAANAAGQAAAAAAJJCaGiNU2NUeQgPU0NDRoHqaaDTBHqZD1B6TaI9SftznzKfZSRJL/ERDO36FU3zSIixKrxKKBJSYMemE9Y047gE9ntIc4nZzJDM0GZoPRhYFWw5owcBC5B4Vtcda+DCX6YKmQbzYOZ3f0dOneoiZOnG9AYUY3JGN7sbC0sk/XFlGzAcm+uQDkAzRcc2L7yDaiO2zlEvSOScLqHmQfmr37u5VuzPPWDN7r7h+RmAc1DApsMiEQ3YXtTjHczI5hE4CkpRUlluJxRbZZAFcyxXErpfIZJQGsQtqLLygulUiNxgSGujKTaY4vLUqrtXWVCm7XEJqnFNbwGIzWVVKKahI38vZiJ7caDg4Jq5uGGAuyOM2nT1JSGg8lRr1pd0isrRpOEWWmzKuVNhAk7EQbPJshoFedkCldmAQQFE0JmKLoCDYqWHQSoNZWDaGrIEZXiwCzO8NoADYgIPN1ctigkIgJlVWnJoRIQy1IiACkfaKw6cCCiJiiIgIEEIsIDygLwT7lwT6hkDH/k2xtmsqDPt5zOC2J0H7fdLVQIlnsLqskY3BBeG8gv2ZKdkDAVblEhFrW6ma8c69paWQsVdaRPolxQsvu1LdUvYR3Vggp1SVkzCL09xmWKEme3WYRPZe1uevo8uRBiqvFt/F4sMF2L6Rdhfk9zVDYOVBC2aFy1z3ILuKcRhi6ach0XCKjS2yBRRJcTC0COnuaf9p/4u5IpwoSFd4QmwA
`
