package testdata

//go:generate ../../../script/testdata_embed.sh unknown_feature_count.fgb
// DO NOT EDIT. Code generated by testdata_embed.sh version 33c7467c340dfc8b64aee4f39e69c704ce29ab56.
//
// This string contains the base64-encoded, bzip2-compressed, contents of the
// file `unknown_feature_count.fgb`. For license information, please see
// https://github.com/gogama/flatgeobuf/flatgeobuf/testdata/flatgeobuf/LICENSE.
//
// Last generated by schapper on Mon 18 Dec 2023 10:14:11 AM PST. The raw source
// SHA-256 is c104be29220ce555dc23339ab26ac1ca016172000aab1db225a5a23becb81fa0.
//
// This silly byte-embedding trick is needed to access the example test code
// when running example code within the docs website,
// https://pkg.go.dev/github.com/gogama/flatgeobuf.
var UnknownFeatureCountFGB = `
QlpoOTFBWSZTWT5whKcAAip////9RFBUb3/hfuf/6r/v/7AQEEABBABEAUyASIEBIgQEwAKWcYi26oNKaaQNT0anmiTamTQAYENDBGQNBkBhBkaAwjAaQT1TxNSeTUM0QAAAAAANAAAAGgAANNCVPU0G1GgD1AaABkAAAAAAAAAABJJGg0pmhAaaRoaA9TQBkekGRoBhH6kbU0NHqaGQ9Tyk7juhgIENrJMjmyqIhHgoUiTV/iBjC1JTo2NwtxCiZVHLgYYYmSAMyYlS8S1FY4E4i2KWNaqIiQLGlCqBKKkIhJckuwRJdmoRIyHVmWJXBRAwg7ASzGtgzmUxXZJTsihlwNostFldY0GLnC7TwceLzvJmDW4rsSSLSLrgCx+lHErLIZsLJRcsXtGvgVelVAVAX5HHDn78A1JB3fN4S8I5JwrCvIOCjZ0tejYfFyNrgzbOU4Kz0IACUNQCTVsUFDUjpStKbTvXzgpoEE8oNCea0tOigzSlSyRrNlADyiVTSxrWzZ6lxFFAA7wFQoVTGvQ+GlVEgjWaInlJIRB0MZJJcxpOJiYIWGuBbZzzAghSGvUAMSPtUUKRNMkYnI2t7SlFE26g29t9Z+5HllMDdO26WhKA0cRCbRyEumSKppJzaFVPTUr6a2BWf8HUzWa2sThNZlpTpMykZA9LKd3lZTt8GWTnSkLDnk+x+GYnkIZrmEBER3MgMqx4ZQADFASOLmOOt10CUiCIxOOur3JoRojRSI4MkOk0EJ821jLKSQQhFzNEL0L2T5y6+Hks7Q8n9TVLgTGDVwGAF0ZUH2irmWphEMFJXVMDnuCNdW0gGYHE9jABAVpvHwINJNZuz7s8JcgbC51yWWIg7+1ap10GYzLhk2x2bGgnuEKXsItS1mZZ8cGibOYRLTa0OLI1OzeQISrAaZ/g5JhKFooIhAOhVMyWYEmpxAHbUO/bMmYgH7jsItyOfKfke1Y/qlUsGxnWAhxqithGNxlyIxp15NiIhxIsI4P4Iw6ePFj/4u5IpwoSB84QlOA=
`
